version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  postgres_db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: channels_manager
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/channels_manager?schema=public
    command: sh -c "npm install && npx prisma migrate dev && npm run dev"
    ports:
      - '5000:5000'
    depends_on:
      - postgres_db
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      VITE_API: http://localhost:5000/api/
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network
